export const mockData = [
  {
    id: 64480,
    rowName: 'Test1',
    total: 2,
    salary: 15420,
    mimExploitation: 0,
    machineOperatorSalary: 0,
    materials: 0,
    mainCosts: 0,
    supportCosts: 0,
    equipmentCosts: 21810,
    overheads: 21480,
    estimatedProfit: 1845,
    isEditing: false,
    child: [
      {
        id: 64504,
        rowName: 'Test2',
        total: 0,
        salary: 1030,
        mimExploitation: 0,
        machineOperatorSalary: 0,
        materials: 0,
        mainCosts: 0,
        supportCosts: 0,
        equipmentCosts: 1454,
        overheads: 1432,
        estimatedProfit: 123,
        child: [],
        isEditing: false,
      },
      {
        id: 64483,
        rowName: 'Test2',
        total: 2,
        salary: 7210,
        mimExploitation: 0,
        machineOperatorSalary: 0,
        materials: 0,
        mainCosts: 0,
        supportCosts: 0,
        equipmentCosts: 10178,
        overheads: 10024,
        estimatedProfit: 861,
        isEditing: false,
        child: [
          {
            id: 64505,
            rowName: 'Test2',
            total: 0,
            salary: 1030,
            mimExploitation: 0,
            machineOperatorSalary: 0,
            materials: 0,
            mainCosts: 0,
            supportCosts: 0,
            equipmentCosts: 1454,
            overheads: 1432,
            estimatedProfit: 123,
            child: [],
            isEditing: false,
          },
          {
            id: 64506,
            rowName: 'Child of Test2',
            total: 1,
            salary: 4120,
            mimExploitation: 0,
            machineOperatorSalary: 0,
            materials: 0,
            mainCosts: 0,
            supportCosts: 0,
            equipmentCosts: 5816,
            overheads: 5728,
            estimatedProfit: 492,
            isEditing: false,
            child: [
              {
                id: 64507,
                rowName: 'Child of Test2 Child1',
                total: 0,
                salary: 1030,
                mimExploitation: 0,
                machineOperatorSalary: 0,
                materials: 0,
                mainCosts: 0,
                supportCosts: 0,
                equipmentCosts: 1454,
                overheads: 1432,
                estimatedProfit: 123,
                child: [],
                isEditing: false,
              },
              {
                id: 64508,
                rowName: 'Child of Test2 Child1',
                total: 0,
                salary: 1030,
                mimExploitation: 0,
                machineOperatorSalary: 0,
                materials: 0,
                mainCosts: 0,
                supportCosts: 0,
                equipmentCosts: 1454,
                overheads: 1432,
                estimatedProfit: 123,
                child: [],
                isEditing: false,
              },
            ],
          },
        ],
      },
    ],
  },
];
